# last updated: 12.05.2017

# install taps
tap 'homebrew/versions'
tap 'caskroom/fonts'

brew 'zsh'
brew 'zsh-completions'
brew 'git'
brew 'curl'
brew 'macvim'
brew 'wget'
brew 'nvm'
brew 'rbenv'
brew 'docker'
brew 'pyenv'
brew 'socat'
brew 'gpg2'
brew 'pinentry'
brew 'pinentry-mac'
brew 'pass'

cask 'iterm2'
# need to open up for oracle installs. do manually
# cask 'virtualbox'
cask 'vagrant'
cask 'google-chrome'
cask 'firefox'
cask 'spotify'
cask 'skype'
cask 'google-backup-and-sync'
cask 'dropbox'
cask 'hammerspoon'
cask 'slack'
# docker cask, for docker for mac, includes docker-compose, docker-machine and client.
cask 'docker'
cask 'atom'
cask 'intellij-idea-ce'
# sad but true xD
cask 'tunnelblick'
cask 'skype-for-business'
